### PR TITLE
MAC_SDK_VERSION 10.14

### PR DESCRIPTION
**Pull request by antonsoroko**
macos version of elementum can be build with it.

for https://github.com/elgatito/plugin.video.elementum/issues/758

### CODE REVIEW

**Comment by elgatito** [comment]
@antonsoroko when you increase SDK version. you increase minimum version of OS, that can run it.
10.12 already compiles fine.

**Comment by antonsoroko** [comment]
https://github.com/tpoechtrager/osxcross#deployment-target

```
DEPLOYMENT TARGET:
The default deployment target is:

SDK <= 10.13: macOS 10.6
SDK >= 10.14: macOS 10.9

However, there are several ways to override the default value:

by passing OSX_VERSION_MIN=10.x to ./build.sh
```

looks like we can use more "high" version of sdk but define "lower" version of OS. will test.

(also looks like be default even for 10.12 target should be 10.6)

**Comment by antonsoroko** [comment]
so libtorrent-go builds fine with 10.6 although it says
`ld: warning: building for macOS 10.6.0 is deprecated`

but it will say the same with default settings
https://github.com/tpoechtrager/osxcross/blob/5771a847950abefed9a37e2d16ee10e0dd90c641/build.sh#L38

but then elementum build fails with
`ld: library not found for -lstdc++`

will try to increase the version.

**Comment by elgatito** [comment]
@antonsoroko Again, why you want to upgrade SDK version? Current SDK 10.12 is properly compiling Elementum.

**Comment by antonsoroko** [comment]
i mean, at some point we will need to update it again. so instead of waiting up until that point, we can "buy" ourselves some extra time.
but it is entirely up to you.

**Comment by antonsoroko** [comment]
so, it works with OSX_VERSION_MIN=10.9 but i had to clear my golang build cache.

we can close this PR and reopen it when needed, if you like.

mostly - i just wanted to test how it works.

**Comment by elgatito** [comment]
@antonsoroko Sadly, to make sure everyone can run elementum, we have to use the oldest version, we can find. That is the reason of using old Debian, which can run on kernel 3.14.

**Comment by antonsoroko** [comment]
ok.

**Pull request closed without merging**
